postgresql:
  enabled: true
  auth:
    username: postgres
    password: password
    database: postgres
    postgresPassword: password
  primary:
    extraEnvVars:
      - name: POSTGRESQL_USERNAME
        value: postgres
      - name: POSTGRESQL_PASSWORD
        value: password
      - name: POSTGRESQL_DATABASE
        value: postgres
      - name: POSTGRES_INITSCRIPTS_USERNAME
        value: postgres
      - name: POSTGRES_INITSCRIPTS_PASSWORD
        value: password

global:
  postgresql:
    auth:
      username: postgres
      password: password
      database: postgres
      postgresPassword: password
    host: postgres
    port: 5432

core:
  image:
    name: gcr.io/informed-ai-prod/informed-core
  extraEnvs:
    - name: DATABASE_CONFIG__DRIVER
      value: "psycopg"
ui:
  image:
    name: gcr.io/informed-ai-prod/informed-ui
    tag: latest


hostname: "informed-ai.org"

ingress:
  enabled: true
  className: gce
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "informed-app-static-ip"
    kubernetes.io/ingress.backend-protocol: HTTP
    networking.gke.io/managed-certificates: informed-cert

certmanager:
  enabled: false  # Disable cert-manager as we're not using a custom domain

# Disable other components that are not needed for this setup
externaldns:
  enabled: false

traefik:
  enabled: false

opentelemetry:
  enabled: false
  config:
    exporters:
      googlecloud:
        project: informed-ai-prod
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [googlecloud]

telemetry:
  enabled: false
